package lazyman;

import Util.Props;
import java.awt.FileDialog;
import java.nio.file.Paths;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Options extends javax.swing.JDialog {

    private Map<String, String> nhl, mlb;
    private String fcb;
    private String hideConsole;
    private boolean go;

    public Options(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        go = false;
        initComponents();

        nhl = new java.util.TreeMap();
        mlb = new java.util.TreeMap();
        setNHLMap();
        setMLBMap();
        
            fcb = Props.getPreferFrench();
            hideConsole = Props.getHideConsole();
            String nhlTeam = Props.getNHLTeam();
            if (!nhlTeam.equals("")) {
                for (Map.Entry<String, String> e : nhl.entrySet()) {
                    if (nhlTeam.equals(e.getValue())) {
                        nhlTeam = (String) e.getKey();
                        break;
                    }
                }
                NHLCB.setSelectedItem(nhlTeam);
            }
            
            String mlbTeam = Props.getMLBTeam();
            if (!mlbTeam.equals("")) {
                for (Map.Entry<String, String> e : mlb.entrySet()) {
                    if (mlbTeam.equals(e.getValue())) {
                        mlbTeam = (String) e.getKey();
                        break;
                    }
                }
                MLBCB.setSelectedItem(mlbTeam);
            }

            if (Props.getPreferFrench().equals("1")) {
                frenchCheckBox.setSelected(true);
            }

            if (!Props.getNHLTeam().equals("") || !Props.getPreferFrench().equals("")) {
                applyBtn.setEnabled(false);
            }

            saveStreamLocTB.setText(Props.getSaveStreamLoc());
            saveStreamLocTB.setCaretPosition(0);

            if (!Props.getStreamLinkArgs().equals("")) {
                slArgTB.setText(Props.getStreamLinkArgs());
            } 
            slArgTB.setCaretPosition(0);
            slArgTB.getInputMap().put(KeyStroke.getKeyStroke("ENTER"),"doNothing");
            
            if (!Props.getMediaPlayerrArgs().equals("") && !Props.getVlcloc().equals("")) {
                mpArgTB.setText(Props.getMediaPlayerrArgs());
            }
            else if (Props.getVlcloc().equals("")) {
                 mpLocTB.setText("Please set your media player location.");
            } 
            mpArgTB.setCaretPosition(0);
            mpArgTB.getInputMap().put(KeyStroke.getKeyStroke("ENTER"),"doNothing");
            
            refreshSpinner.setValue(Props.getRefreshRate());
            
            if (!mpLocTB.getText().equals("")) {
                mpLocTB.setText(Props.getVlcloc());
            }
            
            go = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        NHLCB = new javax.swing.JComboBox<>();
        frenchCheckBox = new javax.swing.JCheckBox();
        applyBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        saveStreamLocTB = new javax.swing.JTextField();
        setSaveBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        slArgTB = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mpArgTB = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        refreshSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        mpLocTB = new javax.swing.JTextField();
        mpLocBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        MLBCB = new javax.swing.JComboBox<>();
        consoleCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Choose your favorite NHL team:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel1, gridBagConstraints);

        NHLCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Anaheim Ducks", "Arizona Coyotes", "Boston Bruins", "Buffalo Sabres", "Calgary Flames", "Carolina Hurricanes", "Chicago Blackhawks", "Colorado Avalanche", "Columbus Blue Jackets", "Dallas Stars", "Detroit Red Wings", "Edmonton Oilers", "Florida Panthers", "Los Angeles Kings", "Minnesota Wild", "Montreal Canadiens", "Nashville Predators", "New Jersey Devils", "New York Islanders", "New York Rangers", "Ottawa Senators", "Philadelphia Flyers", "Pittsburgh Penguins", "San Jose Sharks", "St. Louis Blues", "Tampa Bay Lightning", "Toronto Maple Leafs", "Vancouver Canucks", "Vegas Golden Knights", "Washington Capitals", "Winnipeg Jets" }));
        NHLCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NHLCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(NHLCB, gridBagConstraints);

        frenchCheckBox.setText("Prefer French feeds");
        frenchCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(frenchCheckBox, gridBagConstraints);

        applyBtn.setText("Apply");
        applyBtn.setEnabled(false);
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(applyBtn, gridBagConstraints);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(closeBtn, gridBagConstraints);

        jLabel2.setText("Location to save streams:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel2, gridBagConstraints);

        saveStreamLocTB.setEditable(false);
        saveStreamLocTB.setText("jTextField1");
        saveStreamLocTB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        saveStreamLocTB.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 556;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(saveStreamLocTB, gridBagConstraints);

        setSaveBtn.setText("...");
        setSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSaveBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(setSaveBtn, gridBagConstraints);

        jLabel3.setText("Streamlink Arguments:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel3, gridBagConstraints);

        slArgTB.setColumns(20);
        slArgTB.setLineWrap(true);
        slArgTB.setRows(5);
        slArgTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                slArgTBKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(slArgTB);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 581;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel4.setText("Media Player Arguments:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel4, gridBagConstraints);

        mpArgTB.setColumns(20);
        mpArgTB.setLineWrap(true);
        mpArgTB.setRows(5);
        mpArgTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mpArgTBKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(mpArgTB);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 581;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jLabel5.setText("Refresh Time (in minutes 0 = off):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel5, gridBagConstraints);

        refreshSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        refreshSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                refreshSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(refreshSpinner, gridBagConstraints);

        jLabel6.setText("Media Player Location :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel6, gridBagConstraints);

        mpLocTB.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 556;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(mpLocTB, gridBagConstraints);

        mpLocBtn.setText("...");
        mpLocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpLocBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.ipady = -2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(mpLocBtn, gridBagConstraints);

        jLabel7.setText("Choose your favorite MLB team:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel7, gridBagConstraints);

        MLBCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Arizona Diamondbacks", "Atlanta Braves", "Baltimore Orioles", "Boston Red Sox", "Chicago Cubs", "Chicago White Sox", "Cinncinnati Reds", "Cleveland Indians", "Colorado Rockies", "Detroit Tigers", "Houston Astros", "Kansas City Royals", "Los Angeles Angels", "Los Angeles Dodgers", "Miami Marlins", "Milwaukee Brewers", "Minnesota Twins", "New York Mets", "New York Yankees", "Oakland Athletics", "Philadelphia Phillies", "Pittsburgh Pirates", "San Diego Padres", "San Francisco Giants", "Seattle Mariners", "St. Louis Cardinals", "Tampa Bay Rays", "Texas Rangers", "Toronto Blue Jays", "Washington Nationals" }));
        MLBCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLBCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(MLBCB, gridBagConstraints);

        consoleCheckBox.setText("Hide Console");
        consoleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(consoleCheckBox, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        String team = (String) NHLCB.getSelectedItem();
        Props.setNHLTeam((String) nhl.get(team));
        team = (String) MLBCB.getSelectedItem();
        Props.setMLBTeam((String) mlb.get(team));
        if (frenchCheckBox.isSelected()) {
            Props.setPreferFrench("1");
        } else {
            Props.setPreferFrench("0");
        }
        Props.setSaveStreamLoc(saveStreamLocTB.getText());
        Props.setStreamlinkArgs(slArgTB.getText());
        Props.setMediaPlayerrArgs(mpArgTB.getText());
        Props.setRefreshRate((int) refreshSpinner.getValue());
        Props.setVlcloc(mpLocTB.getText());
        applyBtn.setEnabled(false);
    }//GEN-LAST:event_applyBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void NHLCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NHLCBActionPerformed
        enableApply();
    }//GEN-LAST:event_NHLCBActionPerformed

    private void frenchCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchCheckBoxActionPerformed
        if (frenchCheckBox.isSelected())
            fcb = "1";
        else
            fcb = "0";
        enableApply();
    }//GEN-LAST:event_frenchCheckBoxActionPerformed
    
    private void setSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSaveBtnActionPerformed
        if (System.getProperty("os.name").toLowerCase().contains("mac")) {
            System.setProperty("apple.awt.fileDialogForDirectories", "true");
            
            FileDialog fd = new FileDialog(this, "Choose a folder to save streams", FileDialog.LOAD);
            fd.setDirectory(saveStreamLocTB.getText());
            
            fd.setVisible(true);
            
            String loc = Paths.get(fd.getDirectory(), fd.getFile()).toAbsolutePath().normalize().toString();
            
            if (loc != null) {
                saveStreamLocTB.setText(loc);
            }
            
            System.setProperty("apple.awt.fileDialogForDirectories", "false");
        } else {
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(saveStreamLocTB.getText()));
        chooser.setDialogTitle("Choose a folder to save streams");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            saveStreamLocTB.setText(chooser.getSelectedFile().getAbsolutePath());
        }
                }
        enableApply();
                
    }//GEN-LAST:event_setSaveBtnActionPerformed

    private void slArgTBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_slArgTBKeyReleased
        enableApply();
    }//GEN-LAST:event_slArgTBKeyReleased

    private void mpArgTBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mpArgTBKeyReleased
        enableApply();
    }//GEN-LAST:event_mpArgTBKeyReleased

    private void refreshSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_refreshSpinnerStateChanged
        enableApply();
    }//GEN-LAST:event_refreshSpinnerStateChanged

    private void mpLocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpLocBtnActionPerformed
        String loc;

        if (!System.getProperty("os.name").toLowerCase().contains("win")) {
            FileDialog fd = new FileDialog(this, "Choose Media Player", FileDialog.LOAD);
            if (!Props.getVlcloc().equals("")) {
                fd.setFile(Props.getVlcloc());
            }

            fd.setVisible(true);
            loc = fd.getFile();
            if (loc != null) {
                mpLocTB.setText(Paths.get(fd.getDirectory(), fd.getFile()).toAbsolutePath().normalize().toString());
            }
        } else {
            javax.swing.JFileChooser fileChooser = new JFileChooser();
            if (System.getProperty("os.name").toLowerCase().contains("win")) {
                fileChooser.setFileFilter(new FileNameExtensionFilter("Executable Files", "exe"));
            } else {
                fileChooser.setFileFilter(null);
            }
            if (!Props.getVlcloc().equals("")) {
                fileChooser.setCurrentDirectory(new java.io.File(Props.getVlcloc()));
            }
            int returnVal = fileChooser.showOpenDialog(null);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                loc = fileChooser.getSelectedFile().getPath();
                mpLocTB.setText(loc);
            }
        }
        enableApply();
    }//GEN-LAST:event_mpLocBtnActionPerformed

    private void MLBCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLBCBActionPerformed
        enableApply();
    }//GEN-LAST:event_MLBCBActionPerformed

    private void consoleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleCheckBoxActionPerformed
        if (consoleCheckBox.isSelected())
            hideConsole = "1";
        else
            hideConsole = "0";
        enableApply();
    }//GEN-LAST:event_consoleCheckBoxActionPerformed

    private void setNHLMap() {
        nhl.put("None", "None");
        nhl.put("Ottawa Senators", "OTT");
        nhl.put("Philadelphia Flyers", "PHI");
        nhl.put("New York Rangers", "NYR");
        nhl.put("Washington Capitals", "WSH");
        nhl.put("Calgary Flames", "CGY");
        nhl.put("Winnipeg Jets", "WPG");
        nhl.put("San Jose Sharks", "SJS");
        nhl.put("Los Angeles Kings", "LAK");
        nhl.put("Minnesota Wild", "MIN");
        nhl.put("St. Louis Blues", "STL");
        nhl.put("Pittsburgh Penguins", "PIT");
        nhl.put("Buffalo Sabres", "BUF");
        nhl.put("Montreal Canadiens", "MTL");
        nhl.put("Toronto Maple Leafs", "TOR");
        nhl.put("New Jersey Devils", "NJD");
        nhl.put("Florida Panthers", "FLA");
        nhl.put("Columbus Blue Jackets", "CBJ");
        nhl.put("New York Islanders", "NYI");
        nhl.put("Detroit Red Wings", "DET");
        nhl.put("Carolina Hurricanes", "CAR");
        nhl.put("Boston Bruins", "BOS");
        nhl.put("Tampa Bay Lightning", "TBL");
        nhl.put("Nashville Predators", "NSH");
        nhl.put("Dallas Stars", "DAL");
        nhl.put("Chicago Blackhawks", "CHI");
        nhl.put("Colorado Avalanche", "COL");
        nhl.put("Anaheim Ducks", "ANA");
        nhl.put("Arizona Coyotes", "ARI");
        nhl.put("Edmonton Oilers", "EDM");
        nhl.put("Vancouver Canucks", "VAN");
        nhl.put("Vegas Golden Knights", "VGK");
    }
    
    private void setMLBMap() {
        mlb.put("None", "None");
        mlb.put("Chicago Cubs", "CHC");
        mlb.put("Chicago White Sox", "CWS");
        mlb.put("Oakland Athletics", "OAK");
        mlb.put("Baltimore Orioles", "BAL");
        mlb.put("New York Yankees", "NYY");
        mlb.put("Toronto Blue Jays", "TOR");
        mlb.put("Pittsburgh Pirates", "PIT");
        mlb.put("New York Mets", "NYM");
        mlb.put("Seattle Mariners", "SEA");
        mlb.put("Boston Red Sox", "BOS");
        mlb.put("Arizona Diamondbacks", "ARI");
        mlb.put("Atlanta Braves", "ATL");
        mlb.put("Tampa Bay Rays", "TB");
        mlb.put("Texas Rangers", "TEX");
        mlb.put("Cleveland Indians", "CLE");
        mlb.put("Minnesota Twins", "MIN");
        mlb.put("Detroit Tigers", "DET");
        mlb.put("Houston Astros", "HOU");
        mlb.put("Los Angeles Angels", "LAA");
        mlb.put("Kansas City Royals", "KC");
        mlb.put("Philadelphia Phillies", "PHI");
        mlb.put("Milwaukee Brewers", "MIL");
        mlb.put("Miami Marlins", "MIA");
        mlb.put("St. Louis Cardinals", "STL");
        mlb.put("San Diego Padres", "SD");
        mlb.put("Colorado Rockies", "COL");
        mlb.put("Cincinnati Reds", "CIN");
        mlb.put("Los Angeles Dodgers", "LAD");
        mlb.put("Washington Nationals", "WSH");
        mlb.put("San Francisco Giants", "SF");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MLBCB;
    private javax.swing.JComboBox<String> NHLCB;
    private javax.swing.JButton applyBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JCheckBox consoleCheckBox;
    private javax.swing.JCheckBox frenchCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mpArgTB;
    private javax.swing.JButton mpLocBtn;
    private javax.swing.JTextField mpLocTB;
    private javax.swing.JSpinner refreshSpinner;
    private javax.swing.JTextField saveStreamLocTB;
    private javax.swing.JButton setSaveBtn;
    private javax.swing.JTextArea slArgTB;
    // End of variables declaration//GEN-END:variables

    private void enableApply() {
        if (!go)
            return;
        boolean enable;
        enable = !Props.getNHLTeam().equals(nhl.get(NHLCB.getSelectedItem())) ||
                !Props.getMLBTeam().equals(mlb.get(MLBCB.getSelectedItem())) ||
                !Props.getPreferFrench().equals(fcb) ||
                !Props.getSaveStreamLoc().equals(saveStreamLocTB.getText()) ||
                !Props.getStreamLinkArgs().equals(slArgTB.getText()) ||
                !Props.getMediaPlayerrArgs().equals(mpArgTB.getText()) ||
                Props.getRefreshRate() != (int) refreshSpinner.getValue() ||
                !Props.getVlcloc().equals(mpLocTB.getText());
        applyBtn.setEnabled(enable);
    }
}
